AWSTemplateFormatVersion: '2010-09-09'
Description: Ticket Microservice Fargate Service

Parameters:
  ServiceName:
    Type: String
    Default: printer-service
    Description: Name of the Service

  Application:
    Description: Application Name for which service is being created
    Type: String
    Default: lottery-project

  Environment:
    Description: Which environment the service is created for.
    Type: String
    Default: dev
    ConstraintDescription: Environment can be [dev, qa, prod]
    AllowedValues:
      - dev
      - qa
      - prod

  ContainerCPU:
    Type: Number
    Default: 256
    Description: How much cpu to be given to the container (1024 - 1 CPU)

  ContainerMemory:
    Type: Number
    Default: 512
    Description: How much memory in megabytes to be given to the container

  Image:
    Type: String
    Default: vnair5/printer-service
    Description: Docker image name

  ImageVersion:
    Type: String
    Default: latest
    Description: Docker image version

  DesiredCount:
    Type: Number
    Default: 2
    Description: Desired number of tasks to be run

  Subnets:
    Description: Subnets to which the services should be deployed
    Type: List<AWS::EC2::Subnet::Id>

Resources:
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join [ '', [ !Ref ServiceName, '-task-role'] ]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Tags:
        - Key: Application
          Value: !Ref Application
        - Key: Environment
          Value: !Ref Environment

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref ServiceName
      Cpu: !Ref ContainerCPU
      Memory: !Ref ContainerMemory
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn:
        Fn::ImportValue: !Sub ${Environment}:${Application}:ECSTaskExecutionRole
      TaskRoleArn: !Ref TaskRole
      ContainerDefinitions:
        - Name: !Ref ServiceName
          Image: !Join [":", [ !Ref Image, !Ref ImageVersion] ]
          PortMappings:
            - ContainerPort: 80
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: lottery-project
              awslogs-stream-prefix: !Ref ServiceName
              awslogs-region: ap-south-1
        - Name: !Join [ '-', [!Ref ServiceName, 'xray-sc'] ]
          Image: 'amazon/aws-xray-daemon'
          Portmappings:
            - ContainerPort: 2000
              Protocol: UDP
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: lottery-project
              awslogs-stream-prefix: !Join [ '-', [!Ref ServiceName, '-xray-sc'] ]
              awslogs-region: ap-south-1
          Cpu: 32
          MemoryReservation: 256
      Tags:
        - Key: Application
          Value: !Ref Application
        - Key: Environment
          Value: !Ref Environment

  Service:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Ref ServiceName
      Cluster: !Sub ${Environment}-${Application}-fargate
      LaunchType: FARGATE
      DeploymentConfiguration:
        MaximumPercent: 100
        MinimumHealthyPercent: 50
      DesiredCount: !Ref DesiredCount
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED # can be changed to DISABLED if it is private subnet with NAT gateway
          SecurityGroups:
            - Fn::ImportValue: !Sub ${Environment}:${Application}:ContainerSecurityGroup
          Subnets: !Ref Subnets
      TaskDefinition: !Ref TaskDefinition
      ServiceRegistries:
        - RegistryArn: !GetAtt ServiceDiscovery.Arn
          Port: 80

  ServiceDiscovery:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      Description: Discovery Service for the ticket-service
      DnsConfig:
        RoutingPolicy: WEIGHTED
        DnsRecords:
          - TTL: 60
            Type: A
          - TTL: 60
            Type: SRV
      Name: !Ref ServiceName
      NamespaceId:
        Fn::ImportValue: !Sub ${Environment}-${Application}-LotteryNamespace



Outputs:
  ServiceName:
    Value: !Ref ServiceName



