AWSTemplateFormatVersion: '2010-09-09'
Description: Creates Fargate Cluster

Parameters:
  Application:
    Description: Application Name for which ECS Cluster is being created
    Type: String
    Default: TheBitByteBox
  Environment:
    Description: Which environment the VPC is created for.
    Type: String
    Default: Development
    ConstraintDescription: Environment can be [Development, QA, Production]
    AllowedValues:
      - Development
      - QA
      - Production

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${Environment}-${Application}-fargate
      Tags:
        - Key: Application
          Value: !Ref Application
        - Key: Environment
          Value: !Ref Environment

Outputs:
  ClusterName:
    Description: ECS Cluster Name
    Value: !Ref ECSCluster
    Export:
      Name: !Sub ${Environment}-${Application}-ECSCluster